# Generated by Django 3.0.5 on 2020-05-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='uploads/menu')),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'ordering': ['ordering'],
            },
        ),
    ]
