# Generated by Django 3.0.5 on 2020-05-08 14:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['ordering'], 'verbose_name': 'Меню', 'verbose_name_plural': 'Сторінки меню'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='uploads/menu'),
        ),
    ]
