# Generated by Django 3.0.5 on 2020-04-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('1', 'Готівка'), ('2', 'Термінал')], max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(choices=[('lviv', 'Львів'), ('lviv region', 'Околиці Львова'), ('by-client', 'Самовивіз')], max_length=16),
        ),
    ]
